/** CENTRAL SEO CONFIGURATION — titles, defaults and feature flags used by lib/metadata.ts and lib/schema.ts */
import type { Lang, Localized } from "@/lib/types";

export const seoConfig = {
  titleSuffix: {
    fr: " | Dr Amine Kammoun",
    ar: " | د. أمين قمون",
  } as Localized,
  /** Home / pages that already carry the brand in their own title. */
  titleMaxLength: 70,
  descriptionRange: [90, 165] as [number, number],
  defaultOgImage: "/og/", // generated by app/og/route.tsx
  twitterCard: "summary_large_image" as const,
  /**
   * FAQPage JSON-LD: since 2023 Google shows FAQ rich results only for well-known government and
   * health authority sites. Keep OFF unless that situation changes; FAQs stay visible in the page body.
   */
  enableFaqSchema: false,
  /** Areas named in structured data (`areaServed`) and on the local page. */
  areaServed: [
    { fr: "Ain Zaghouan Nord", ar: "عين زغوان الشمالية" },
    { fr: "Ain Zaghouan", ar: "عين زغوان" },
    { fr: "L'Aouina", ar: "العوينة" },
    { fr: "Cité El Wahat", ar: "حي الواحات" },
    { fr: "La Soukra", ar: "سكرة" },
    { fr: "Lac 2", ar: "البحيرة 2" },
    { fr: "Les Berges du Lac", ar: "ضفاف البحيرة" },
    { fr: "Grand Tunis", ar: "تونس الكبرى" },
  ] as Localized[],
};

export function pageTitle(lang: Lang, metaTitle: string, withSuffix = true): string {
  if (!withSuffix) return metaTitle;
  const full = `${metaTitle}${seoConfig.titleSuffix[lang]}`;
  // Keep titles within the SERP display range: drop the suffix when the title is already long.
  return full.length > 68 ? metaTitle : full;
}

/** Origin used for the per-area "directions from…" links on the service-areas page (section id → place). */
export const AREA_ORIGINS: Record<string, string> = {
  "ain-zaghouan": "Ain Zaghouan, Tunis",
  aouina: "L'Aouina, Tunis",
  "cite-wahat": "Cité El Wahat, Tunis",
  soukra: "La Soukra, Tunis",
  lac: "Lac 2, Les Berges du Lac, Tunis",
  "grand-tunis": "Tunis",
};
